// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TCGSplashScreen","status":true,"description":"Displays a Splash Screen before the title screen","parameters":{"Splash Text":"Tiny Country Games Presents","Splash length":"5","Skip if File Exists":"true"}},
{"name":"TCGDungeons","status":true,"description":"Displays Dungeon information in a dungeon","parameters":{}},
{"name":"TCGCustomTitleScreen","status":true,"description":"Allows for custom title screen","parameters":{"Credit at Bottom":"true","Prefix Credit":"Created By","Developer Name":"José Rodriguez-Rivas"}}
];
