// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CustomTitleScreen","status":true,"description":"Allows for custom title screen","parameters":{"Credit at Bottom":"true","Prefix Credit":"Created By","Developer Name":"José Rodriguez-Rivas"}}
];
