// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TCGSplashScreen","status":false,"description":"Displays a Splash Screen before the title screen","parameters":{"Splash Text":"Tiny Country Games Presents","Splash length":"5","Skip if File Exists":"false"}},
{"name":"TCGSplashScreen_Movie","status":false,"description":"Displays a Splash Screen before the title screen","parameters":{"Splash Movie":"splash","Skip if File Exists":"false"}},
{"name":"TCGControlScreen","status":true,"description":"Creates a screen where all the controls of the game are displayed.","parameters":{}},
{"name":"TCGDungeons","status":true,"description":"Displays Dungeon information in a dungeon","parameters":{}},
{"name":"TCGCustomTitleScreen","status":true,"description":"Allows for custom title screen","parameters":{"Credit at Bottom":"true","Prefix Credit":"Created By","Developer Name":"José Rodriguez-Rivas"}},
{"name":"TCGDayNight","status":true,"description":"Implements a day/night cycle based on system time","parameters":{}}
];
